name = "cf-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2025-11-12"
minify = true

[[kv_namespaces]]
binding = "SIREN"
id = "f35490ce191e4d7289968b2cf5a76427"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "f282b878-8711-45a1-8c69-5564172123c1"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/RaikazuWebId/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/RaikazuWebId/Siren/refs/heads/master/web/sub.html"
